version: "3.9"

services:
  bioinfo:
    restart: always
    build: .
    tty: true
    image: project-bio-info_bioinfo
    #image: bioinfoc
    container_name: valtest
  # volumes: #pour relier la machine au conteneur
  #   - .:/home/Sudies/ProjetBioInfo

